version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/pinterest_like
hooks:
  Applicationstop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  Beforeinstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  Applicationstart:
    - location: scripts/application_start.sh
      timeout: 600
      runas: ec2-user